id: P23179104
initial_creation_type: ocr
source_metadata:
  volumes:
    805b1ad1b59f48509a13e674dcbbb3cf:
      base_file: v063.txt
      image_group_id: I1PD95908
      title: བདེན་པ་གཉིས་ལ་འཇུག་པ།
      total_pages: 1926
      volume_number: 63
